"""
KSE Markdown Report Exporter.

Generates a human-readable engineering report summarizing the synthesised
knowledge across all 5 levels of understanding.
"""

from __future__ import annotations

import io
from pathlib import Path
from typing import IO

from ..models import SystemModel


class MarkdownReportExporter:
    """Exports the synthesised SystemModel as a formatted Markdown document."""

    def export(self, model: SystemModel, output: Path | str | IO[str]) -> None:
        """Export the system model.

        Parameters:
            model: The synthesised SystemModel.
            output: Target file path or stream.
        """
        report = self.generate_report(model)

        if isinstance(output, (str, Path)):
            with open(output, "w", encoding="utf-8") as f:
                f.write(report)
        else:
            output.write(report)

    def generate_report(self, model: SystemModel) -> str:
        """Compile the Markdown report string."""
        sb = io.StringIO()

        # Title
        sb.write("# Lyme - KSE System Synthesis Report\n\n")
        sb.write("> [!NOTE]\n")
        sb.write("> This report was automatically generated by the Knowledge Synthesis Engine (KSE).\n")
        sb.write("> It represents interpretable operational knowledge extracted entirely from observation logs.\n\n")

        # Dataset overview
        sb.write("## 1. System Metadata & Telemetry Overview\n\n")
        sb.write("| Parameter | Value |\n")
        sb.write("|---|---|\n")
        sb.write(f"| Unique Variables | {len(model.variable_names)} |\n")
        sb.write(f"| Timestamps Analyzed | {model.timestamp_count} |\n")
        sb.write(f"| Discovered Relationships (L2) | {len(model.relationships)} |\n")
        sb.write(f"| Discovered Rules (L3) | {len(model.rules)} |\n")
        sb.write(f"| Discovered Operational Modes (L4) | {len(model.modes)} |\n")
        sb.write(f"| Active Contradictions Detected | {len(model.contradictions)} |\n\n")

        # Level 5
        sb.write("## 2. Discovered Causal Structure (Level 5)\n\n")
        if model.relationships:
            sb.write("```mermaid\nflowchart TD\n")
            # Build list of active nodes
            active_vars = set()
            for r in model.relationships:
                active_vars.add(r.source)
                active_vars.add(r.target)

            for var in active_vars:
                sb.write(f'    {var}["{var}"]\n')

            for r in model.relationships:
                lag_str = f" delay {r.estimated_lag:.3g}s" if r.estimated_lag > 0 else ""
                label = f"{r.relation_type.value}{lag_str} (conf: {r.confidence:.2f})"
                sb.write(f'    {r.source} -->|"{label}"| {r.target}\n')
            sb.write("```\n\n")
        else:
            sb.write("*No strong causal dependencies found to construct a graph flow.*\n\n")

        # Level 4: Operational Modes & Transitions
        sb.write("## 3. System Operational Modes (Level 4)\n\n")
        if model.modes:
            sb.write("### Discovered Modes\n\n")
            for mode in model.modes:
                sb.write(f"#### 🟢 {mode.label} (Prevalence: {mode.prevalence * 100:.1f}%)\n\n")
                sb.write(f"**Description**: {mode.description}\n\n")
                sb.write("**Dominant Centroid Features**:\n")
                for feat in mode.distinguishing_features:
                    val = mode.centroid.get(feat, 0.0)
                    sb.write(f"- `{feat}`: **{val:.4g}**\n")
                sb.write("\n")

            if model.mode_transitions:
                sb.write("### Probabilistic Transitions\n\n")
                sb.write("| From Mode | To Mode | Count | Probability | Confidence |\n")
                sb.write("|---|---|---|---|---|\n")
                for trans in model.mode_transitions:
                    sb.write(
                        f"| {trans.from_mode} | {trans.to_mode} | {trans.count} | "
                        f"{trans.probability * 100:.1f}% | {trans.confidence:.2f} |\n"
                    )
                sb.write("\n")
        else:
            sb.write("*No operational modes identified in the state space.*\n\n")

        # Level 3: Rules
        sb.write("## 4. Multi-Variable Threshold Rules (Level 3)\n\n")
        if model.rules:
            sb.write("| Rule | Confidence | Support | Precision | Evidence Level |\n")
            sb.write("|---|---|---|---|---|\n")
            for r in model.rules:
                rule_text = r.to_text().replace("|", "\\|")
                sb.write(
                    f"| `{rule_text}` | {r.confidence:.2f} | {r.support * 100:.1f}% | "
                    f"{r.precision * 100:.1f}% | {r.evidence_level.value} |\n"
                )
            sb.write("\n")
        else:
            sb.write("*No clear conditional threshold rules discovered.*\n\n")

        # Level 2: Directed Relationships
        sb.write("## 5. Directed Variable Relationships (Level 2)\n\n")
        if model.relationships:
            sb.write("| Source | Target | Type | Est. Lag | Confidence | Methods |\n")
            sb.write("|---|---|---|---|---|---|\n")
            for r in model.relationships:
                methods = ", ".join(r.supporting_methods)
                sb.write(
                    f"| `{r.source}` | `{r.target}` | {r.relation_type.value} | "
                    f"{r.estimated_lag:.3g} | {r.confidence:.2f} | {methods} |\n"
                )
            sb.write("\n")
        else:
            sb.write("*No directed pairwise relationships found.*\n\n")

        # Level 1: Static Observations
        sb.write("## 6. Static Observations & Correlations (Level 1)\n\n")
        if model.findings:
            sb.write("| Variables | Description | Metric | Value | Confidence | Level |\n")
            sb.write("|---|---|---|---|---|---|\n")
            for f in model.findings[:50]: # Limit to top 50
                vars_str = ", ".join(f.variables)
                sb.write(
                    f"| {vars_str} | {f.description} | {f.metric_name} | "
                    f"{f.metric_value:.3f} | {f.confidence:.2f} | {f.evidence_level.value} |\n"
                )
            sb.write("\n")
        else:
            sb.write("*No significant static correlations observed.*\n\n")

        # Contradictions
        sb.write("## 7. Contradictions & Alternating Explanations\n\n")
        if model.contradictions:
            for c in model.contradictions:
                sb.write(f"> [!WARNING]\n")
                sb.write(f"> **{c.description}**\n")
                sb.write(f"> - Evidence A: *{c.finding_a}*\n")
                sb.write(f"> - Evidence B: *{c.finding_b}*\n\n")
        else:
            sb.write("*No contradictory evidence found. Discovered model is internally consistent.*\n\n")

        return sb.getvalue()
