#!/usr/bin/env python3
"""Command-Line Interface (CLI) for the Operational Model Synthesizer (OMS).
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
import pandas as pd

from ..kse.models import (
    SystemModel,
    Finding,
    Relationship,
    Rule,
    Condition,
    OperationalMode,
    ModeTransition,
    RelationType,
    EvidenceLevel,
    KnowledgeGraph,
)
from . import OMSConfig, OperationalModelSynthesizer
from .exporters import (
    MarkdownTheoryExporter,
    JSONTheoryExporter,
    DigitalTwinPythonExporter,
)


def reconstruct_system_model(input_dir: Path) -> SystemModel:
    """Load and parse JSON files generated by Component 2 to rebuild the SystemModel."""
    rel_file = input_dir / "kse_relationships.json"
    rules_file = input_dir / "kse_rules.json"
    graph_file = input_dir / "kse_graph.json"

    for f in (rel_file, rules_file, graph_file):
        if not f.exists():
            raise FileNotFoundError(f"Required KSE output file not found: {f}")

    # 1. Load Relationships and Findings
    with open(rel_file, "r", encoding="utf-8") as f:
        rel_data = json.load(f)

    relationships = []
    for r in rel_data.get("relationships", []):
        relationships.append(
            Relationship(
                source=r["source"],
                target=r["target"],
                relation_type=RelationType(r["relation_type"]),
                confidence=r["confidence"],
                evidence_level=EvidenceLevel(r["evidence_level"]),
                estimated_lag=r.get("estimated_lag", 0.0),
                lag_confidence=r.get("lag_confidence", 0.0),
                p_value=r.get("p_value"),
                data_coverage=r.get("data_coverage", 1.0),
                supporting_methods=r.get("supporting_methods", []),
                metadata=r.get("metadata", {}),
            )
        )

    findings = []
    for f_item in rel_data.get("findings", []):
        findings.append(
            Finding(
                variables=f_item["variables"],
                description=f_item["description"],
                confidence=f_item["confidence"],
                evidence_level=EvidenceLevel(f_item["evidence_level"]),
                metric_name=f_item["metric_name"],
                metric_value=f_item["metric_value"],
                data_coverage=f_item.get("data_coverage", 1.0),
                p_value=f_item.get("p_value"),
                method=f_item.get("method", ""),
                metadata=f_item.get("metadata", {}),
            )
        )

    # 2. Load Rules
    with open(rules_file, "r", encoding="utf-8") as f:
        rules_data = json.load(f)

    rules = []
    for ru in rules_data.get("rules", []):
        conditions = []
        for c in ru.get("conditions", []):
            conditions.append(
                Condition(
                    variable=c["variable"],
                    operator=c["operator"],
                    threshold=c["threshold"],
                )
            )
        rules.append(
            Rule(
                conditions=conditions,
                target_variable=ru["target_variable"],
                outcome_description=ru["outcome_description"],
                confidence=ru["confidence"],
                evidence_level=EvidenceLevel(ru["evidence_level"]),
                support=ru.get("support", 0.0),
                precision=ru.get("precision", 0.0),
                p_value=ru.get("p_value"),
                metadata=ru.get("metadata", {}),
            )
        )

    # 3. Load Graph and Extract Modes & Transitions
    with open(graph_file, "r", encoding="utf-8") as f:
        graph_data = json.load(f)

    modes = []
    variable_names = []
    mode_transitions = []

    for n in graph_data.get("nodes", []):
        if n["type"] == "variable":
            variable_names.append(n["id"])
        elif n["type"] == "mode":
            meta = n["metadata"]
            centroid = meta.get("centroid", {})
            prevalence = meta.get("prevalence", 0.0)
            dist_feat = meta.get("distinguishing_features", [])
            desc = meta.get("description", "")
            
            total_count = rel_data.get("metadata", {}).get("timestamps_analyzed", 1000)
            member_count = int(prevalence * total_count)

            modes.append(
                OperationalMode(
                    label=n["id"],
                    description=desc,
                    centroid=centroid,
                    member_count=member_count,
                    total_count=total_count,
                    distinguishing_features=dist_feat,
                    confidence=meta.get("confidence", 0.8),
                )
            )

    for e in graph_data.get("edges", []):
        if e["relation_type"] == "transitions_to":
            meta = e.get("metadata", {})
            mode_transitions.append(
                ModeTransition(
                    from_mode=e["source"],
                    to_mode=e["target"],
                    count=meta.get("count", 1),
                    probability=meta.get("probability", 0.5),
                    confidence=e["confidence"],
                )
            )

    graph = KnowledgeGraph()
    contradictions = []

    return SystemModel(
        findings=findings,
        relationships=relationships,
        rules=rules,
        modes=modes,
        mode_transitions=mode_transitions,
        graph=graph,
        contradictions=contradictions,
        variable_names=variable_names,
        timestamp_count=rel_data.get("metadata", {}).get("timestamps_analyzed", 0),
        metadata=graph_data.get("metadata", {}),
    )


def main() -> None:
    # Reconfigure console output to UTF-8 to prevent encoding crashes on Windows
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")

    parser = argparse.ArgumentParser(
        description="Cognis OS — Operational Model Synthesizer (OMS) CLI"
    )
    parser.add_argument(
        "--input-dir",
        type=str,
        default="output_processed",
        help="Directory containing KSE synthesised files (relationships, rules, graph JSONs)",
    )
    parser.add_argument(
        "--matrix",
        type=str,
        default="output_processed/aligned_state_matrix.csv",
        help="Path to the aligned state matrix CSV from Component 1",
    )
    parser.add_argument(
        "--output-dir",
        type=str,
        default="output_processed",
        help="Directory to save the synthesized theory and Digital Twin",
    )
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    matrix_path = Path(args.matrix)
    output_dir = Path(args.output_dir)

    print("==================================================")
    print("1. Reconstructing system model from KSE outputs...")
    try:
        model = reconstruct_system_model(input_dir)
        print(
            f"   ✓ Loaded {len(model.variable_names)} variables, {len(model.relationships)} relationships, "
            f"{len(model.rules)} rules, and {len(model.modes)} operational modes."
        )
    except Exception as e:
        print(f"Error loading system model: {e}", file=sys.stderr)
        sys.exit(1)

    print("\n==================================================")
    print("2. Loading aligned telemetry state matrix...")
    df = None
    if matrix_path.exists():
        try:
            df = pd.read_csv(matrix_path)
            print(f"   ✓ Ingested state matrix from {matrix_path} ({len(df)} rows).")
        except Exception as e:
            print(f"Warning: Failed to load aligned state matrix: {e}. Falling back to metadata-only synthesis.")
    else:
        print(f"Warning: State matrix '{matrix_path}' not found. Deriving equations using mode centroids only.")

    print("\n==================================================")
    print("3. Executing Operational Model Synthesizer...")
    config = OMSConfig(verbose=True)
    synthesizer = OperationalModelSynthesizer(config)
    theory = synthesizer.synthesize(model, df=df)

    print("\n==================================================")
    print("4. Exporting synthesized operational theory assets...")
    output_dir.mkdir(parents=True, exist_ok=True)

    report_path = output_dir / "oms_report.md"
    json_path = output_dir / "oms_model.json"
    twin_path = output_dir / "digital_twin.py"

    # Export Human-Readable Markdown report
    MarkdownTheoryExporter().export(theory, report_path)
    print(f"   ✓ Operational Theory Report:  {report_path}")

    # Export Machine-Readable JSON model
    JSONTheoryExporter().export(theory, json_path)
    print(f"   ✓ JSON Operational Model:    {json_path}")

    # Export Runnable Digital Twin
    DigitalTwinPythonExporter().export(theory, twin_path)
    print(f"   ✓ Runnable Digital Twin code: {twin_path}")

    print("\n==================================================")
    print("Operational Model Synthesis completed successfully!")
    print("You can now review the markdown report or run the digital twin using:")
    print(f"  python {twin_path}")


if __name__ == "__main__":
    main()
